name: mis_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  pin_code_fields: ^8.0.1
  get: 4.6.6
  get_storage: ^2.1.1
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - .env
    - assets/vectors/auth/
    - assets/vectors/home/
    - assets/vectors/
    - assets/images/

